name: ReVanced build
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Leaving blank will be the latest version that revanced support builds. You can build the latest version of YouTube, but errors may occur. Example: 17.35.36'
        required: false
        default: 'Default'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      FEATURE:
        description: 'Turn off the feature, Add spaces to distinguish each feature'
        required: false
        default: 'always-autorepeat hide-autoplay-button custom-video-speed copy-video-url '
      ICONS:
        description: 'Original icon & Name'
        required: false
        type: boolean
        default: true
      OPTIMIZATION:
        description: 'Video loaded speed'
        required: false
        type: boolean
        default: true
      SHORTS:
        description: 'Show button shorts video'
        required: false
        type: boolean
        default: true
      ROUND:
        description: 'Pip rounded (root)'
        required: false
        type: boolean
        default: true

jobs:
  get_next_version_code:
    runs-on: ubuntu-22.04
    outputs:
      NEXT_VER: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 77
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get next version code
        id: next_ver_code
        run: |
          echo "NEXT_VER_CODE=$(TZ='Asia/Ho_Chi_Minh' date +"%Y.%m.%d-%H.%M.%S")" >> $GITHUB_OUTPUT
          # TAG=$(git tag --sort=creatordate | tail -1)
          # fetch it from github
          # TAG=$(wget https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest -O- | tr -d ' ' | sed -n 's/.*"tag_name":"\(.*\)".*/\1/p')
          # if [ -z "$TAG" ]; then TAG=0; fi
          # echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT

  build1:
    name: 'NO ROOT...'
    runs-on: ubuntu-22.04
    needs: get_next_version_code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Get sqlite3
        run: bash ./get_sqlite3.sh
      - name: Get MicroG
        run: bash ./get_microg.sh
      - name: Build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'true'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=true; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button custom-video-speed copy-video-url"; AMOLED=true; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          . .github/install.sh

      - name: Get build log
        id: get_output
        run: |
          bash ./buildlog.sh
          echo -e "\nYouTube version: ${{ env.VS }}" >>build.md
          echo -e "\nUse [MicroG APK](https://github.com/inotia00/VancedMicroG/releases/latest/download/microg.apk) for YouTube and Music" >>build.md
          echo -e "\n[Revanced-tool repo]($GITHUB_SERVER_URL/${{ github.repository }})" >>build.md
       
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up/*
          release_name: Revanced-v${{ env.VS }}
          tag: ${{ needs.get_next_version_code.outputs.NEXT_VER }}
          file_glob: true
          overwrite: true

  build2:
    name: 'ROOT...'
    runs-on: ubuntu-22.04
    needs: get_next_version_code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Get sqlite3
        run: bash ./get_sqlite3.sh
      - name: Get MicroG
        run: bash ./get_microg.sh
      - name: Build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'false'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=false; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button custom-video-speed copy-video-url"; AMOLED=true; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          . .github/install.sh

      - name: Upload json
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up*.json
          tag: Up
          file_glob: true
          prerelease: true
          overwrite: true

      - name: Get build log
        id: get_output
        run: |
          bash ./buildlog.sh
          echo -e "\nYouTube version: ${{ env.VS }}" >>build.md
          echo -e "\nUse [MicroG APK](https://github.com/inotia00/VancedMicroG/releases/latest/download/microg.apk) for YouTube and Music" >>build.md
          echo -e "\n[Revanced-tool repo]($GITHUB_SERVER_URL/${{ github.repository }})" >>build.md
       
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up/*
          release_name: Revanced-v${{ env.VS }}
          tag: ${{ needs.get_next_version_code.outputs.NEXT_VER }}
          file_glob: true
          overwrite: true

  build3:
    name: 'AMOLED NO ROOT...'
    runs-on: ubuntu-22.04
    needs: get_next_version_code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Get sqlite3
        run: bash ./get_sqlite3.sh
      - name: Get MicroG
        run: bash ./get_microg.sh
      - name: Build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'false'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'true'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=true; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button custom-video-speed copy-video-url"; AMOLED=false; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          . .github/install.sh

      - name: Get build log
        id: get_output
        run: |
          bash ./buildlog.sh
          echo -e "\nYouTube version: ${{ env.VS }}" >>build.md
          echo -e "\nUse [MicroG APK](https://github.com/inotia00/VancedMicroG/releases/latest/download/microg.apk) for YouTube and Music" >>build.md
          echo -e "\n[Revanced-tool repo]($GITHUB_SERVER_URL/${{ github.repository }})" >>build.md
       
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up/*
          release_name: Revanced-v${{ env.VS }}
          tag: ${{ needs.get_next_version_code.outputs.NEXT_VER }}
          file_glob: true
          overwrite: true

      - name: Switch to update branch
        run: git checkout -f update || git switch --discard-changes --orphan update

      - name: Update changelog
        id: update_config
        run: |
          cp -f build.tmp build.md
          CHANGELOG_URL="https://raw.githubusercontent.com/${{ github.repository }}/update/build.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: build.md
          commit_message: Bump version ${{ needs.get_next_version_code.outputs.NEXT_VER }}
          push_options: '-f -u'

  build4:
    name: 'AMOLED ROOT...'
    runs-on: ubuntu-22.04
    needs: get_next_version_code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Get sqlite3
        run: bash ./get_sqlite3.sh
      - name: Get MicroG
        run: bash ./get_microg.sh
      - name: Build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'false'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'false'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=false; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button custom-video-speed copy-video-url"; AMOLED=false; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          . .github/install.sh

      - name: Upload json
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up*.json
          tag: Up
          file_glob: true
          prerelease: true
          overwrite: true

      - name: Get build log
        id: get_output
        run: |
          bash ./buildlog.sh
          echo -e "\nYouTube version: ${{ env.VS }}" >>build.md
          echo -e "\nUse [MicroG APK](https://github.com/inotia00/VancedMicroG/releases/latest/download/microg.apk) for YouTube and Music" >>build.md
          echo -e "\n[Revanced-tool repo]($GITHUB_SERVER_URL/${{ github.repository }})" >>build.md
       
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Up/*
          release_name: Revanced-v${{ env.VS }}
          tag: ${{ needs.get_next_version_code.outputs.NEXT_VER }}
          file_glob: true
          overwrite: true

  Notify:
    needs:
      - build1
      - build2
      - build3
      - build4
    uses: ./.github/workflows/notify.yml
    secrets: inherit
